### ISSUE TITLE
ADV mode

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-answer#12]
(chat excerpt)

> so what I did is parse the script and try to guess how long each page is (like, lines of text), assuming even character spacing (it's not really even)
> then, my program is meant to force a 'page turn' (clear the screen) if the page exceeds a certain lines of text
> but i haven't done that yet
> uuuh I also played around moving the window on the screen, that's easy
> that's as far as I got, but the hard part is done I think
> I was just not sure what it was meant to look like
> I saw your picture you posted though
> In terms of patching the script, my plan is to make a patcher which will convert the script to ADV mode. I don't think it's feasible to have a switching option. We can run the patcher each time we release a new script, or alternatively have the users run it on their computer

MOCKUP IMAGE:
[honeyview_1515003151_6572139804](https://user-images.githubusercontent.com/1249449/34550456-33f5f67c-f165-11e7-9900-68dd413dd8e6.jpg)
  
Reminder to self that fort's font doesn't support japanese characters - need a workaround of some sort or find unicode version of that font.

**Comment by Forteissimo** [comment]
Comparison between fonts:
http://screenshotcomparison.com/comparison/127931

Text box image files:
[Textboxes.zip](https://github.com/07th-mod/umineko-answer/files/1608360/Textboxes.zip)

Window values for the default game font, Noto Sans CJK JP - It supports Japanese characters but has a very extreme line separation. Fontlab crashes whenever I try to edit this font. Takes up about 4 lines.
`setwindow 73,363,36,17,23,23,0,2,20,1,1,msgwnd,50,356`

Window values for a modified version of Source Sans (which appears to be essentially the same font as Noto Sans) with a less promintent line separation. Takes up about 5 lines.
`setwindow 73,369,33,17,26,26,0,2,20,1,1,msgwnd,50,356`

You can find the font here, rename it to 'face0.otf'. Be wary that this _only_ includes the regular weight.
[sourceedit5.zip](https://github.com/07th-mod/umineko-answer/files/1608365/sourceedit5.zip)

**Comment by drojf** [comment]
Here's a game script with my fix applied so max lines before text is cleared is 5 (although sometimes I predict incorrectly and it goes to 6 lines I think): https://cdn.discordapp.com/attachments/384427969520599043/399834741831892993/adv_mode_test.zip

I used the 'textclear' function, I think this may look slightly different from a normal page turn, not sure.

Had to reduce the number of characters per line from 33 to 32 (the second argument). You can text this requirement by making a line with 250 `.` characters and seeing where it wraps.

edit: the text cursor also looks a bit funky: 
![image](https://user-images.githubusercontent.com/1249449/34662203-fbb146f4-f4a2-11e7-9b4f-c704f69d4e8b.png)

**Comment by drojf** [comment]
I worked a bit more on the ADV mode. In short, this version only modifies existing 'clickwaits' in the script (`@` symbol) to be page breaks (`@/`). The old version didn't do this and was somewhat unpredictable in it's results.

Attached is the latest ADV script:
[0.zip](https://github.com/07th-mod/umineko-answer/files/1668162/0.zip)

I think it's mostly there, just a few things to sort out:

- [ in progress ] I haven't seen it overflow the text box yet, but I haven't tested all that much of the game.
- [ in progress ]Some sections need to be manually fixed/marked. My code has the ability to ignore sections of the script - you just have to paste some text to mark the start/stop of the region. We can use that for the special sections (probably can extract them from the umitweak script actually)
- [x] The text window appears during startup of the game and in some other places (not a big deal, should be easy to fix). Likely it always did that, but was masked because the text window is black normally.
- [X] The bold text of the font is much larger than the normal text of the font which gives a funny effect.
- [X]The font doesn't support japanese characters (I haven't actually tested what happens if you do try and show japanese characters) EDIT: Fixed using this tool: https://github.com/source-foundry/font-line which can edit the default font files (fontforge doesn't open it properly)
- [x] OPTIONAL Add character names - I got this working but I need a textbox for each character with their name on it. Can use the method in photoshop where you input a list of text where each line is the character's name and it generates it automatically. Theoretically could also include the length of the textbox for each image if you wanted in the .csv file so the text box size always matches. Before actually doing this I need to fix something (the text box displays even when the setwindow isn't set to use a textbox image...)

Known problems

- [unfixable, probably] the cursor is drawn BEHIND the text box. This results in the cursor being grey instead of white. This is because the cursor is drawn by the script, but the window is drawn by the game automatically, ontop of everything else. I looked into fixing this - you can use the `windowback` function to set the window at the same level as the standing sprites (standing sprite layer set by `humanz`). Unfortunately this screws everything up to do with the standing sprites (their default layer is 900, which is underneath everything else). Umitweak couldn't/didn't fix this either (I checked their game). It's not a big deal but it's annoying. You could potentially fix it by overriding the `ld` function, but I'm pretty sure  that would break stuff, and isn't worth the effort.

- backlog doesn't clear until the screen is next redrawn

----

Some stuff I found out (or didn't bother to pay attention to earlier):

- Every time you advance a clickwait, a the *text_cw function is called (this is set by `textgosub *text_cw`). This function handles various things, including rendering the cursor
- There is a 'pretext' handler (see `pretextgosub`), which is called just before text is displayed. You can insert tags in the text and the pretextt handler will receive them (see the docs). The docs even say **Pretext tag processing is especially intended for handling names and voice files for dialog text.** - we were probably supposed to use them for doing the voice files. Potentially could add the "character names on the text window" with that. This is assuming the game supports pretext tag handling. Even without it we can just insert the character names into the script anyway (or extract it from the last played voice file?). 
- EDIT - THIS FUNCTION DOESNT EXIST There is a function called `windowchip` which attaches a sprite to the text window (it fades in/out with the text window). Probably intended for character portraits, we can use it for the character names. 
- the `strsp` function can be used to create a sprite out of text. We can use this to display the character names. (I probably should have used it to do the subtitles for the end movie but I didn't know the function existed) EDIT - this can't be used - it works but you can't set the font the text is drawn with EDIT2: you can use the logsp function instead?

- You can 
    - `getcursorpos` will get the current cursor position after a clickwait (when the game is waiting for a click to progress). 
    - `gettext` retrieves the text which is currently in the text buffer. 
    - `ispage` tells you whether the clickwait is for a 'next page'
    - `textbtnwait` tells you what button was pressed during a clickwait. We could potentially use this to allow increasing/decreasing the volume at runtime or other actions. `btnwait2` tells you what buttons are available. The game currently uses it to display the backlog, advance text, etc in the function `text_cw`
    - `getini` can retrieve variables from .ini file - it might not be implented in this version of the game though.

I don't think this is enough information to do the word wrap entirely by script but it will probably be useful for something else.

<details>
```
; override dwave so can extract which character is talking
; the function stores the current character in $Free28
*dwave
	getparam %witchh13, $witchh17
	_dwave %witchh13, $witchh17

	len %Free28, $witchh17
	if %Free28 < 10 jumpf
		mid $Free27, $witchh17, 0,5 
		if $Free27 != "voice" jumpf

		mid $Free28, $witchh17, 6, 2

		if $Free28 == "10" setwindow2 ":b;tb_battler.png"
		if $Free28 == "30" setwindow2 ":b;tb_virg.png"
		mov %Free29, 1

	~
return
```

```
;*************************************
;文章表示前の割り込みルーチン
*pretext
	if %save_on_flg = on saveon
	if %Free29 == 0 setwindow2 ":b;TextBox1_2.png"
return
;*************************************
```

```
<in *text_cw>
ispage %Textcc12Flug    ;クリック待ちか、改ページか
if %Textcc12Flug == 1 mov %Free29, 0
```

edit: better version

```
add in defsub dwave

<in top of *text_cw>
ispage %Textcc12Flug    ;クリック待ちか、改ページか
if %Textcc12Flug == 1 mov $Free29,":b;TextBox1_2.png"
<end in *text_cw>

;*************************************
;文章表示前の割り込みルーチン
*pretext
	if %save_on_flg = on saveon
	if $Free26 != $Free29 setwindow2 $Free29 : mov $Free26,$Free29
return
;*************************************

; override dwave so can extract which character is talking
; the function stores the current character in $Free28
*dwave
	getparam %witchh13, $witchh17
	_dwave %witchh13, $witchh17

	len %Free28, $witchh17
	if %Free28 < 10 jumpf
		mid $Free27, $witchh17, 0,5 
		if $Free27 != "voice" jumpf

		mid $Free28, $witchh17, 6, 2

                ;insert different charcter windows here - will need to alter 
                ;setwindow to fit increased size but that's easy.
		if $Free28 == "10" mov $Free29,":b;tb_battler.png"  
		if $Free28 == "30" mov $Free29,":b;tb_virg.png"
	~
return
```
</details>

**Comment by Forteissimo** [comment]
Thanks a lot for taking the time to work on it. Sorry about the bold fonts, I was meaning to upload those earlier but it slipped my mind. For some reason, there are three copies of the same font file - replaced them all just to be sure. There are also a bunch of other fonts but I ignored those as I don't think they're even used in the first place.

[fonts.zip](https://github.com/07th-mod/umineko-answer/files/1670468/fonts.zip)

This is how Japanese characters are displayed with the current font.

![japanesecharacters](https://user-images.githubusercontent.com/20634116/35475741-41cdcdd0-0360-11e8-8503-4395ee54c17e.png)

Whereas Noto Sans CJK JP seems impossible to modify without Fontlab crashing on me, Sazanami Gothic (face4.ttf), came through just fine. I could see it working if you could somehow call the font in the script in the same way as the bold command. Note that Sazanami Gothic is .ttf.

![japfont](https://user-images.githubusercontent.com/20634116/35476817-d15d8bda-0373-11e8-85e3-164056c61013.png)

[sazanamigothic.zip](https://github.com/07th-mod/umineko-answer/files/1670591/sazanamigothic.zip)

As for the backlog, I uploaded a script which fixed it (and also slightly changed the position values for the window image as it was a little offset relative to the original game) a week or so ago, dunno if you saw it. The '*text_cw_lookback2' segment in the script is changed to:

```
*text_cw_lookback2
notif %cur_read_lang = 0 goto *text_cw_lookback2_jp

btndef ""
  ;ボタン配置

   lsp backscreen,":b;TextBox1_2.png",47,355  ;convert to widescreen
   lsp backlogupbtn,":b;bmp\system\UONCUR.png",47,355     ;座標は仮  ;convert to widescreen
   lsp backlogdownbtn,":b;bmp\system\DONCUR.png",47,500  ;convert to widescreen


  ;ボタンセット

  ;テキストセット

itoa $Free1,%backloglook          ;ログ表示

   logsp backlogtext,$%backloglook,147,738,#FFFFaa  ;convert to widescreen
```

While the setwindow command is changed to:

`setwindow 73,369,32,17,26,26,0,2,20,1,1,":b;TextBox1_2.png",47,355`


This is what the backlog looks like.

![screenshot 576](https://user-images.githubusercontent.com/20634116/35475797-2bf26532-0362-11e8-8f86-3a8f3a55d132.png)

Regarding the name window, it'd be amazing if you could actually manage to get it working! I refrained from asking about it as I recall the guys at UT mentioned how implementing it would be way too troublesome.

In the original game, the window stretches itself to fit the name displayed, so to replicate that, I figured multiple window images which already include the name of whoever's talking could be used.

![option1](https://user-images.githubusercontent.com/20634116/35477333-ad905c3c-037d-11e8-8713-18294cef7f2c.png)

Alternatively, we could settle for a single image every name could fit on and let them display through text.

![option2](https://user-images.githubusercontent.com/20634116/35477335-afe659aa-037d-11e8-8ee1-f8328ce1e439.png)

**Comment by drojf** [comment]
Here's a pack for you to test the ADV mode + named textboxes. 

- I haven't fixed disabling the text box in 'special' scenes but that should be easy
- All beatrices use the default beatrice name (may need to change the names on some of the textboxes
- Need to fix when character is being introduced to use ????? as the textbox
- The bold font doesn't quite line up with the normal font?

https://drive.google.com/file/d/1YyNgkdz1EJ02KQxXIr9UY_7rujXHsrtC/view?usp=sharing

In the pack is:
- Fonts with spacing adjusted using the `font-line` tool to 20%. I only adjusted font 0 and font 1
- Textboxes
- Updated script

**Comment by Forteissimo** [comment]
Looks fantastic so far! I can't thank you enough for tackling the ADV mode.
Something that bugs me a bit, though, is how the text just breaks away a little from the text box's inner margin at the bottom. 

![example01](https://user-images.githubusercontent.com/20634116/35764994-aba934ac-0878-11e8-8391-ecf5b13578de.png)

I feel it'd look better if the upper and lower margins were even.
The setwindow values for this look are: 

`setwindow 73,368,32,17,24,24,0,0,20,1,1,(...)`

![example02](https://user-images.githubusercontent.com/20634116/35765014-275acc32-0879-11e8-833d-cb7434cb542c.png)

You've got to replace face2 and face3 for the bold text to align properly. They're the same font as face 1.
By the way, is it just me or do saves not work on this script?

**Comment by drojf** [comment]
I fixed up the save problem. The game records your save points with regards to japanese lines (`langjp` in the script)....and I commented out all japanese lines to fix a certain problem.

I still haven't gone through all the 'special' text sequences (when the adv textbox is not used) yet, so expect them to be broken/offset. But most of them actually look 'good enough' from my testing.

## You need to rename the 'none.png' image I posted earlier to '-1.png' . It can be found in the 'textbox' folder! If you don't do this, the 'no name' textbox won't display.

[0_adv_fix_save.zip](https://github.com/07th-mod/umineko-answer/files/1702015/0_adv_fix_save.zip)

**Comment by drojf** [comment]
Alright, I've reviewed and fixed up the special text sequences. I was trying to copy umitweak's formatting before, but various things are different, so now I just vertically center the text, and horizontally center the text if applicable. 

Download for Normal script (0.utf), and test sequence script. The test sequence script shows all 'special text' sequences (about 150):

[ADV Mode 10-02-18.zip](https://github.com/07th-mod/umineko-answer/files/1713207/ADV.Mode.10-02-18.zip)


The main thing left to do would be to put the name as ????? where a new character is introduced/shouldn't be known - either manually or see below:

I was looking at the ps3 script the other day and it seems to indicate the name for every Japanese line.  Theoretically could extract the names from that which would improve the 'named textbox' mode. Haven't looked into it too much though.

I also added the option to just use ADV mode without named textboxes - you just delete 01.png and the game will detect that image is missing and just use the default adv textbox ("-1.png"). Technically this mode is already complete and playable (excusing any bugs I have created).

If I missed fixing anything you mentioned before let me know - I was mainly trying to fix the special text sequences so I probably overlooked other stuff.

**Comment by drojf** [comment]
I managed to extract the names from the script, which should be easy to associate with voiced lines. @Forteissimo - will need you to do up a couple more named textboxes for the missing people (...Maybe you've done them, I haven't checked yet. See name list at bottom of this post.)

Porting the names over for voiced lines is easy, as the voice lines are unique/ easy to match up. I wondered how many times there was a named textbox when there wasn't a voice on a line, and it only happened 120 times. Furthermore, those lines were  mostly just "....". All of those cases are listed below:

<details>
<summary> Click to show unvoiced but named lines</summary>

```
noname: 178 発言者 rイベグラ  []
noname: 179 発言者 rイベグラ  []
noname: 201 発言者 rイベグラ  []
noname: 205 発言者 rイベグラ  []
noname: 209 発言者 rイベグラ  []
noname: 212 発言者 rイベグラ  []
noname: 219 発言者 rイベグラ  []
noname: 221 発言者 rイベグラ  []
noname: 227 発言者 rイベグラ  []
noname: 238 発言者 rイベグラ  []
noname: 253 エヴァオバサン rﾊ〜ｲ､ボクエヴァオバサンｰ｡  []
noname: 286 ベアトリーチェ r｢･････････････｣  []
noname: 296 ベアトリーチェ r｢･･･････････｣  []
noname: 298 ベアトリーチェ r｢･･･････････｣  []
noname: 425 ベアトリーチェ r｢･･････････｣  []
noname: 467 ベアトリーチェ r｢････････････｣  []
noname: 519 呂ノ上　源次 r｢････････｣  []
noname: 1171 ベアトリーチェ r｢･･････････｣  []
noname: 1174 ベアトリーチェ r｢･････････｣  []
noname: 1176 ベアトリーチェ r｢･････････｣  []
noname: 1178 ベアトリーチェ r｢･････････｣  []
noname: 1180 ベアトリーチェ r｢･････････｣  []
noname: 1182 ベアトリーチェ r｢･･････････････････････････････････････････････････････｣  []
noname: 1235 ベアトリーチェ r｢････････････｣  []
noname: 1249 ベアトリーチェ r｢･･･････････｣  []
noname: 1251 ベアトリーチェ r｢･･･････････｣  []
noname: 1315 ベアトリーチェ r｢･････････････｣  []
noname: 1318 ベアトリーチェ r｢･･････････｣  []
noname: 1382 ベアトリーチェ r｢･･･････････｣  []
noname: 1388 ベアトリーチェ r｢･･･････････｣  []
noname: 1399 ベアトリーチェ r｢････････｣  []
noname: 1405 ベアトリーチェ r｢･･････････｣  []
noname: 1413 ベアトリーチェ r｢･･････････｣  []
noname: 1420 ベアトリーチェ r｢･･････････｣  []
noname: 1818 ベアトリーチェ r｢････････････｣  []
noname: 2745 ベアトリーチェ r｢･･･････････｣  []
noname: 2747 ベアトリーチェ r｢･･･････････｣  []
noname: 2766 ベアトリーチェ r｢･･･････････｣  []
noname: 2771 ベアトリーチェ r｢･･･････････｣  []
noname: 2788 ベアトリーチェ r｢･･･････････｣  []
noname: 2814 ベアトリーチェ r｢････････････｣  []
noname: 2833 ベアトリーチェ r｢････････････｣  []
noname: 2844 ベアトリーチェ r｢････････････｣  []
noname: 3489 ベアトリーチェ r｢･････････････｣  []
noname: 3505 ベアトリーチェ r｢･････････････｣  []
noname: 4662 右代宮　戦人 r｢･･･････････｣  []
noname: 5017 ベアトリーチェ r｢･････････････｣  []
noname: 5030 ベアトリーチェ r｢････････････｣  []
noname: 5032 ベアトリーチェ r｢････････････｣  []
noname: 5146 ベアトリーチェ r｢････････････｣  []
noname: 5152 ベアトリーチェ r｢････････････｣  []
noname: 5159 ベアトリーチェ r｢････････････｣  []
noname: 5354 右代宮　戦人 r｢･･･････｣  []
noname: 5872 古戸　ヱリカ r｢･････････｣  []
noname: 5934 ベアトリーチェ r｢･････････････｣  []
noname: 5945 ベアトリーチェ r｢･････････････｣  []
noname: 6044 右代宮　戦人 r｢････････｣  []
noname: 7584 右代宮　縁寿 r｢･････････｣  []
noname: 7816 呂ノ上　源次 r｢･････････｣  []
noname: 7985 ベアトリーチェ r｢････････｣  []
noname: 7989 ベアトリーチェ r｢････････｣  []
noname: 7993 ベアトリーチェ r｢･･････････｣  []
noname: 9241 右代宮　戦人 r｢･･････････｣  []
noname: 9859 呂ノ上　源次 r｢･･･････｣  []
noname: 11252 右代宮　楼座 r｢････････････､｣  []
noname: 11558 右代宮　縁寿 r｢･･･････････｣  []
noname: 12156 ドラノール r｢･･････････｣  []
noname: 12292 ドラノール r｢･････････｣  []
noname: 13222 ドラノール r｢･････････｣  []
noname: 13992 ドラノール r｢･･････････････｣  []
noname: 13995 ドラノール r｢･･････････｣  []
noname: 14692 ベアトリーチェ r｢････････････｣  []
noname: 15659 呂ノ上　源次 r｢････････｣  []
noname: 16166 紗音 r｢｣  []
noname: 16293 呂ノ上　源次 r｢････････････｣  []
noname: 16308 呂ノ上　源次 r｢･･････････｣  []
noname: 18454 呂ノ上　源次 r｢････････････｣  []
noname: 20697 呂ノ上　源次 r｢･･････････｣  []
noname: 20716 呂ノ上　源次 r｢････････｣  []
noname: 20914 呂ノ上　源次 r｢･････････････｣  []
noname: 21268 呂ノ上　源次 r｢･･･････････｣  []
noname: 21272 呂ノ上　源次 r｢･･･････････｣  []
noname: 22615 右代宮　縁寿 r｢･･･････････｣  []
noname: 24991 ラムダデルタ r｢･･･････････｣  []
noname: 26094 古戸　ヱリカ r｢････････｣  []
noname: 26347 右代宮　縁寿 r｢･････････････｣  []
noname: 26539 右代宮　縁寿 r｢･･･････････｣  []
noname: 27852 エンジェ・ベアトリーチェ r｢･･････････｣  []
noname: 28152 エンジェ・ベアトリーチェ r｢･･･････････｣  []
noname: 28360 八城　十八 r｢･･･ﾅｶﾅｶ寝付ｹﾏｾﾝでｼﾀ｡kだｶﾗ､幾子ｻﾝﾉ書ｲﾀ原稿ｦ読ﾝでｲﾏｼﾀ｣  []
noname: 28362 八城　十八 r｢全部読ﾐ終ｴﾏｼﾀ｣  []
noname: 28364 八城　十八 r｢私ﾓ驚ｲﾃｲﾏｽ｡k･･夢中ﾆﾅｯﾃｲﾀﾗ､ｱｯﾄｲｳ間ﾆ読ﾒﾃｼﾏｯﾃ｡k･･文章ｦ斜ﾒﾆ読ﾑﾄｲｳｶ､原稿用紙全体ｦ一度ﾆ見ﾙﾄｲｳべｷｶ･･｣  []
noname: 28366 八城　十八 r｢ﾄﾃﾓ面白ｶｯﾀでｽ｡kﾀだ､海流ﾆﾂｲﾃﾉ説明がﾓｳ少ｼﾅｲﾄ､推理小説ﾄｼﾃﾊアンフェアｶﾓｼﾚﾏｾﾝﾈ･｡kでﾓ､指輪ﾆﾂｲﾃﾉ伏線が､冒頭ｶﾗ出ﾃｲﾀﾉﾊ､ﾄﾃﾓ面白ｶｯﾀでｽ｣  []
noname: 28367 八城　十八 r｢･･･読ﾐ終ｴﾀ後ﾆ､ﾓｳ一度最初ﾆ戻ﾘ､ﾔﾗﾚﾀﾄ思ﾜず手ｦ打ｯﾃｼﾏｲﾏｼﾀ｡kｿｳｲｳ気持ﾁｺｿ､推理小説ﾉ醍醐味だﾄ思ｲﾏｽ｣  []
noname: 28369 八城　十八 r｢･･ｱﾉ､･･何ｶ悪ｲｺﾄｦ言ｯﾀでｼｮｳｶ｡k･･だｯﾀﾗ､ごﾒﾝﾅｻｲ｣  []
noname: 28406 八城　十八 r｢･･幾子ｻﾝﾊ､ﾅぜｺﾉ原稿ｦ誰ｶﾆ見ｾﾖｳﾄｼﾅｲﾉでｽｶ｣  []
noname: 28408 八城　十八 r｢例ｴば､どｺｶﾉ出版社ﾆ応募ｼﾃﾐﾙﾄｶ｡k･･幾子ｻﾝﾉ作品ﾊ､ﾄﾃﾓ面白ｲﾉﾆ､残念でｽﾖ｣  []
noname: 28410 八城　十八 r｢ｱﾚだｹ古今東西ﾉ様々ﾅ推理小説ﾆ精通ｼﾃｲﾃ､素人ﾄｲｳｺﾄﾊﾅｲﾄ思ｲﾏｽ｣  []
noname: 28412 八城　十八 r｢･･誰ﾆﾓ見ｾﾅｲ小説ｦ書ｸｺﾄﾊ､本当ﾆ楽ｼｲでｽｶﾟ｣  []
noname: 28414 八城　十八 r｢今ﾊﾟ｣  []
noname: 28421 八城　十八 r｢大丈夫でｽ｡kｿﾚﾖﾘ原稿ｦ｡k新章が楽ｼﾐでｽ｣  []
noname: 28429 八城　十八 r｢ﾄﾃﾓ良ｲﾄ思ｲﾏｽ･･｡k|y最後ﾉ別ﾚが悲ｼｸ､推理物ﾄｼﾃだｹでﾅｸ､読ﾐ物ﾄｼﾃﾓ厚ﾐが出ﾀﾄ思ｲﾏｽ｣  []
noname: 28431 八城　十八 r｢私ﾊアイデアｦ出ｼﾀだｹでｽ｡kｿﾚｦ､ｺｺﾏで立派ﾅ読ﾐ物ﾆ昇華ｼﾃｸﾚﾀﾉﾊ､全ﾃ幾子ｻﾝﾉ筆ﾉｵ陰でｽ｣  []
noname: 28443 八城　十八 r｢･･･幾子ｻﾝ｡k提案がｱﾙﾝだｹﾚど､ｲｲでｽｶ｣  []
noname: 28445 八城　十八 r｢ｺﾉ私ﾀﾁﾉ作品ｦ､投稿ｼﾃﾐﾏｾﾝｶ｡k･･私ﾊ､ｺﾚﾎど面白ｲ作品ｦ読ﾝだｺﾄがｱﾘﾏｾﾝ｡kｷｯﾄ､読ﾐﾀｲﾄ願ｳ人が大勢現ﾚﾙﾊずでｽ｣  []
noname: 28447 八城　十八 r｢私ﾊ､幾子ｻﾝﾉ才能ｦ確信ｼﾃｲﾏｽ｡k･･幾子ｻﾝﾊどｳでｽｶ｣  []
noname: 28449 八城　十八 r｢ﾅﾗ､決ﾏﾘでｽ｡k･･幾子ｻﾝﾉ､メジャｰデビュｰｦ祈ｯﾃ｣  []
noname: 28459 八城　十八 r｢･･幾子ｻﾝ｡k明ｶﾘｦﾂｹﾃ下ｻｲ｡k･･ｺﾝﾅ暗ｲ部屋でパソコンじｬ､目ｦ悪ｸｼﾏｽﾖ｣  []
noname: 28461 八城　十八 r｢ｲｴ､ぐｯｽﾘ眠ｯﾃｲﾏｼﾀ｡kｵ陰様で､頭ﾓｽｯｷﾘでｽ｣  []
noname: 28463 八城　十八 r｢ﾋどｲ雨でｽﾈ｡k風ﾓﾋどｲ｡kﾏﾀ雨どｲが葉ｯぱで詰ﾏﾗﾅｲﾄｲｲﾉでｽが｣  []
noname: 28466 八城　十八 r｢幾子ｻﾝﾊ､最近ﾊｶﾅﾘパソコンﾆ熱心ﾅﾖｳでｽﾈ｡k何ｶ面白ｲ記事でﾓｱﾘﾏｽｶﾟ｣  []
noname: 28468 八城　十八 r｢･･六軒島･･･ﾟ｣  []
noname: 28475 八城　十八 r｢･･頭が､･･･痛ｲ･･･････｣  []
noname: 28850 古戸　ヱリカ r｢･････････････｣  []
noname: 30350 古戸　ヱリカ r｢･･･････････｣  []
noname: 32893 ベアトリーチェ r｢･･･････････｣  []
noname: 32924 ベアトリーチェ r｢･････････････｣  []
noname: 32934 ベアトリーチェ r｢･････････････｣  []
noname: 32984 ベアトリーチェ r｢･･･････････｣  []
noname: 33265 右代宮　戦人 r｢･･････････････｣  []
```
</details>

For now I'm going to leave these alone. They mostly add clarity to the '...' bits, except for that one section (I haven't checked what that section is)

I also collected all the names and printed only the unique ones. A couple names need new textboxes if we want to match the name. Left is the English name, middle is the voice / textbox number, right is the Japanese name as it appears in the game. These should be all the possible names in the entire game.

<details>
<summary> Click to show names </summary>

```
Use Default Textbox  :  -1 : None
Ushiromiya Kinzo     :   1 : 右代宮　金蔵
Ushiromiya Krauss    :   2 : 右代宮　蔵臼
Ushiromiya Natsuhi   :   3 : 右代宮　夏妃
Ushiromiya Jessica   :   4 : 右代宮　朱志香
Ushiromiya Eva       :   5 : 右代宮　絵羽
Ushiromiya Hideyoshi :   6 : 右代宮　秀吉
Ushiromiya George    :   7 : 右代宮　譲治
Ushiromiya Rudolf    :   8 : 右代宮　留弗夫
Ushiromiya Kirie     :   9 : 右代宮　霧江
Ushiromiya Battler   :  10 : 右代宮　戦人
Ushiromiya Ange      :  11 : 右代宮　縁寿
Ushiromiya Rosa      :  12 : 右代宮　楼座
Ushiromiya Maria     :  13 : 右代宮　真里亞
Genji Ronoue         :  14 : 呂ノ上　源次
Shannon              :  15 : 紗音
Kannon               :  16 : 嘉音
Toshiro Gohda        :  17 : 郷田　俊朗
Chiyo Kumasawa       :  18 : 熊沢　チヨ
Terumasa Nanjo       :  19 : 南條　輝正
Juuza Amakusa        :  20 : 天草　十三
Tetsuro Okonogi      :  21 : 小此木　鉄郎
Professor Ootsuki    :  23 : 大月教授
Captain Kawabata     :  24 : 川畑船長
Beatrice             :  27 : ベアトリーチェ
Bernkastel           :  28 : ベルンカステル
Lambdadelta          :  29 : ラムダデルタ
Virgilia             :  30 : ワルギリア
Ronove               :  31 : ロノウェ
Gap                  :  32 : ガァプ
Sakutarou            :  33 : さくたろう
Chiester 45          :  35 : シエスタ４５
Chiester 410         :  36 : シエスタ４１０
Chiester 00          :  37 : シエスタ００
Lucifer              :  38 : ルシファー
Leviathan            :  39 : レヴィアタン
Satan                :  40 : サタン
Belphegor            :  41 : ベルフェゴール
Mamon                :  42 : マモン
Beezelbub            :  43 : ベルゼブブ
Asmodeus             :  44 : アスモデウス
Furudo Erika         :  46 : 古戸　ヱリカ
Dlanor               :  47 : ドラノール
Gertrude             :  48 : ガートルード
Cornelia             :  49 : コーネリア
Featherine           :  50 : フェザリーヌ
Zepar                :  51 : ゼパル
Furfur               :  52 : フルフル
Ushiromiya Lion      :  53 : 右代宮　理御
Willard H. Wright    :  54 : ウィラード・Ｈ・ライト
Clair                :  55 : クレル
Ikuko Hachijo        :  56 : 八城　幾子
Tohya Hachijo        :  57 : 八城　十八
Eva Obasan           : ??? : エヴァオバサン
Ange Beatrice        : ??? : エンジェ・ベアトリーチェ
Eva Beatrice         : ??? : エヴァ・ベアトリーチェ
Kotobuki Yukari      : ??? : 寿ゆかり
Ane Beatrice         : ??? : 姉ベアトリーチェ
```
</details>

----

Ones I think are missing

* 'エヴァオバサン':['Eva Obasan', '???'], #This is her name during the "quiz" section # I think this is missing
* 'エンジェ・ベアトリーチェ':['Ange Beatrice', '???'], # I think this is missing
* '寿ゆかり':['Kotobuki Yukari', '???'], # I think this is missing


Ones which I've got

* '八城　十八':['Tohya Hachijo', 57], # you gave me this one #57 is battler's duplicate voice folder for tohya
* 'エヴァ・ベアトリーチェ':['Eva Beatrice', '???'],  # you gave me this one
* '姉ベアトリーチェ':['Ane Beatrice', '???'], 

[Here is a video](https://youtu.be/pJeNgvi33nY?t=14m27s) of when a character has a voiced line but no name shown.


# TODO BEFORE RELEASE:
- [ ] Check drojf_print_snow section (golden snow)

**Comment by drojf** [comment]
Alright, I think I've more or less fixed everything. Just waiting on a couple updated textboxes from fort (just two had the name in slightly the wrong position) and then can probably do a release.

(link removed)

**Comment by drojf** [comment]
Fort informed me that the backlog was broken - there was an error in my script which caused those lines not to be replaced which is now fixed. 

Here is a pack containing the fonts, textboxes, and new script for adv mode to work: 

https://mega.nz/#!ASQXHKKC!J0XaDKi0fXHLDvbeh04kY7bDnt66dZFI5D653a3EF-E

If this is ok, we'll use this as the release version (i'll put the script on github so we can track changes if there are any, and add the files to the proper place instead of on mega).

**Comment by drojf** [comment]
Alright, I've posted a usable script + install instructions at the very bottom of the wiki install page: https://github.com/07th-mod/guide/wiki/Umineko-Part-1---Voice-and-Graphics-Patch

I still need to upload the Python scripts I used to generate ADV mode - the idea was to use the script to regenerate the ADV mode script any the the main script changes. So I won't close this issue for now.

**Comment by drojf** [comment]
ADV mode has been relatively trouble free fora  year now, so it's time to close this issue.
