### ISSUE TITLE
Various asset fixes (Reminder issue)

### ISSUE THREAD

**Issue by drojf** [07th-mod/umineko-answer#47]
This issue can be closed once the following resources have been incorporated into the update zip/a new update zip:

- [x] _Kanon description with the right character_ CONFIRMED
- [x] _fixed image for a typo in some option on Bern's puzzle_ CONFIRMED
- [x] _a button for the Volume menu option, **just gotta change the image being called on the script**_ CONFIRMED
- [x] _Eva button covering the F choice on the quiz sections. Just gotta replace the images in 'en\bmp\quiz' and change the 30,330 values to 30,330 and 130,459 to 144,478 in the area around 'if %quiz_Num < 4 : jumpf' on the script_ CONFIRMED

ADV mode fixes:
- [x] Included here are the default textbox images with the japanese name order 
- [x] plus the black+logo alternative textbox,  (add button to switch textbox?)
- [x] drojf - also might as well fix the 'font overwriting' issue while at it

Updated resources download: https://drive.google.com/file/d/1w8OkP9T3D03pgzTh25FUyM7RuJTTxlp6/view

The related issues should also be closed as this occurs.

Thanks @Forteissimo

**Comment by drojf** [comment]
> This oughta fix the ask Eva button covering the F choice on the quiz sections. Just gotta replace the images in 'en\bmp\quiz' and change the 30,330 values to 30,330 and 130,459 to 144,478 in the area around 'if %quiz_Num < 4 : jumpf' on the script

resources: https://drive.google.com/open?id=1x-CcAJ5OUk39ok-p6gVKbm26bjsc5BGG

~status - partially fixed, but need instructions on 30,330 fix (said to change 30, 330 to 30, 330 which is the same)~ just need to test that it worked

**Comment by Petsnew** [comment]
>Included here are the default textbox images with the japanese name order

Done

>plus the black+logo alternative textbox, (add button to switch `textbox?)

Done (https://github.com/07th-mod/umineko-answer/commit/67bf4f029bbe74fed49d5272dd4ae0a2d6b39f50)
>also might as well fix the 'font overwriting' issue while at it

Done (https://github.com/07th-mod/umineko-answer/commit/7bc6856d28d063da9c4da8ec4fa8c5085573ff03, https://github.com/07th-mod/umineko-answer/commit/e5269c1a1850cf144c5aac2719343c2b48775ec8)
